alias gitclean="git branch | grep -v "master" | xargs git branch -d"
alias gitprune="git remote prune origin"

alias giit="git status"
alias diff="git diff ."
alias master="git checkout master"
alias develop="git checkout develop"
alias fetch="git fetch"
alias pullm="git pull origin master"
alias pulld="git pull origin develop"